
import localFont from "next/font/local";
import "./globals.css";

import { AppDataProvider } from "./context/AppDataContext";
// import React, { useState } from "react";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Touhidul Islam",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  // const [loading, setLoading] = useState(true);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        <AppDataProvider>
          {children}
        </AppDataProvider>

      </body>
    </html>
  );
};
